### ISSUE TITLE
Flashing Leaflet control

### ISSUE THREAD

**Issue by satrock1** [GIAPspzoo/L.TileLayer.Canvas#13]
from the question https://github.com/Leaflet/Leaflet/issues/8361 I was given the answer that I need to use Canvas, but if I write as in the example
```
const config = {
       attribution: '&copy; <a href="https://openstreetmap.org">OpenStreetMap</a>'
     };

     L.tileLayer.canvas('https://c.tile.openstreetmap.org/{z}/{x}/{y}.png', config)
       .addTo(map);
```
then, I still have objects blinking and disappearing.
Tested in Firefox, IE, Chrome browsers. No blinking only in Firefox.
Map became from Canvas and layers are still img

**Comment by marlo22** [comment]
Hello @satrock1 :smile: 
Sorry for the late reply, but I have a lot of work and I didn't notice your thread.

> Map became from Canvas and layers are still img

This is because you set only the OSM layer as a canvas layer and it doesn't change too much when it comes to performance. Try to use `L.tileLayer.canvas` for the other layers too.
